server_url: 'nodejs.landogatsbydrupal.internal:8000'
incrementalbuild_url: ''
build_published: 1
preview_entity_types:
  node: node
  block_content: 0
  content_moderation_state: 0
  file: 0
  media: 0
  menu_link_content: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
path_mapping: ''
